### ISSUE TITLE
Bug: Unflatten handles escaped paths incorrectly

### ISSUE THREAD

**Issue by steurer** [GFoley83/JsonFlatten#1]
It appears that unflatten does not handle escaped paths correctly if they contain a '.' or whitespace-symbol. If a JObject is flattened via Flatten(), it cannot be restored to its original state using unflatten().

```csharp
var flattened = JObject.Parse("{\"outer\":{\"inner.path\": 1}}").Flatten();
// Returns Dictionary with key = outer['inner.path'] and value = 1, as expected

var unflattened = flattened.Unflatten()
// Returns a nested structure
// {
//  "outer": {
//   "'inner": {
//      "path'": 1
//    }
//  }
//}

// Expected result of Unflatten():
// {
//  "outer": {
//   "inner.path": 1
//  }
//}
```

**Comment by jim-craane** [comment]
I have the same issue here. Can this bug be fixed?

**Comment by GFoley83** [comment]
Issue has been resolved in the latest version. Thanks.

**Comment by vickyrajsharma** [comment]
@GFoley83 build is failing due .net framework issue, could you please fix it.

![image](https://user-images.githubusercontent.com/1567117/160927965-1251988e-9940-4428-9e2f-4ad9bed626fe.png)

![image](https://user-images.githubusercontent.com/1567117/160928316-fe148f5d-a718-4df5-b692-b0db26e435b8.png)

**Comment by GFoley83** [comment]
Hi @vickyrajsharma. This can be ignored; appveyor was never setup correctly and I've removed it now.
