### ISSUE TITLE
Invalid index exception due to JSON path containing number

### ISSUE THREAD

**Issue by gjvanvuuren** [GFoley83/JsonFlatten#4]
Thanks for a very useful package.

In a JSON sent by an IOT device, the following path causes an index exception to be thrown when calling ``Unflatten``:

``Data.Data.Dimensions.-00705309.Width.Min``

It seems that ``GetArrayIndex(pathSegment)`` incorrectly interprets the numeric path segment to be an array index.

**Comment by danil-1-1** [comment]
Hi, I added PR to the repository with solution that helped me in case of numeric nodes in my code.

**Comment by GFoley83** [comment]
Hey @daniil-ismagilov @gjvanvuuren apologies for the slow turnaround here. I've just pushed out an update to address this.
I've added the scenario to the test project and also created a dotnetfiddle here to demonstrate the fix:
https://dotnetfiddle.net/AfFVqB

Thanks again.
