### ISSUE TITLE
Unflatten doesn't work when there is a field with a space

### ISSUE THREAD

**Issue by Fierori** [GFoley83/JsonFlatten#6]
Problematic file with (json content):
{
"profiles": {
  "http": {
    "commandName": "Project",
    "dotnetRunMessages": true,
    "launchBrowser": true,
    "launchUrl": "swagger",
    "applicationUrl": "http://localhost:5178",
    "environmentVariables": {
      "ASPNETCORE_ENVIRONMENT": "Development"
    }
  },
  "https": {
    "commandName": "Project",
    "dotnetRunMessages": true,
    "launchBrowser": true,
    "launchUrl": "swagger",
    "applicationUrl": "https://localhost:7236;http://localhost:5178",
    "environmentVariables": {
      "ASPNETCORE_ENVIRONMENT": "Development"
    }
  },
  "IIS Express": {
    "commandName": "IISExpress",
    "launchBrowser": true,
    "launchUrl": "swagger",
    "environmentVariables": {
      "ASPNETCORE_ENVIRONMENT": "Development"
    }
  }
}
}

Unflatten - does not work for prop "IIS Express"

**Comment by GFoley83** [comment]
Thanks @Fierori. Please fork the example Fiddle here and update it to demonstrate the issue you're seeing:

https://dotnetfiddle.net/jYghhm

I'll try and have a look over the weekend. Thanks.

**Comment by Fierori** [comment]
Приношу извинения, все работает корректно

**Comment by Fierori** [comment]
I apologize, everything works correctly

**Comment by Fierori** [comment]
Problematic file with (json content) - when "IIS Express" there is a space in the nested property how is it here json:
{
  "nestedProfiles": {
    "profiles2": {
      "http": {
        "commandName": "Project",
        "dotnetRunMessages": true,
        "launchBrowser": true,
        "launchUrl": "swagger",
        "applicationUrl": "http://localhost:5178",
        "environmentVariables": {
          "ASPNETCORE_ENVIRONMENT": "Development"
        }
      },
      "https": {
        "commandName": "Project",
        "dotnetRunMessages": true,
        "launchBrowser": true,
        "launchUrl": "swagger",
        "applicationUrl": "https://localhost:7236;http://localhost:5178",
        "environmentVariables": {
          "ASPNETCORE_ENVIRONMENT": "Development"
        }
      },
      "IIS Express": {
        "commandName": "IISExpress",
        "launchBrowser": true,
        "launchUrl": "swagger",
        "environmentVariables": {
          "ASPNETCORE_ENVIRONMENT": "Development"
        }
      }
    }
  },
  "profiles": {
    "http": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "launchUrl": "swagger",
      "applicationUrl": "http://localhost:5178",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "https": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "launchUrl": "swagger",
      "applicationUrl": "https://localhost:7236;http://localhost:5178",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "swagger",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}


Сode sketch:

var jContent = JsonContentExamples.GetJsonLaunchSettings();
var jObject = JObject.Parse(jContent);
var flatten = jObject.Flatten();
var restore = flatten.Unflatten();
Console.WriteLine(restore);

View result:
{
  "nestedProfiles": {
    "profiles2": {
      "http": {
        "commandName": "Project",
        "dotnetRunMessages": true,
        "launchBrowser": true,
        "launchUrl": "swagger",
        "applicationUrl": "http://localhost:5178",
        "environmentVariables": {
          "ASPNETCORE_ENVIRONMENT": "Development"
        }
      },
      "https": {
        "commandName": "Project",
        "dotnetRunMessages": true,
        "launchBrowser": true,
        "launchUrl": "swagger",
        "applicationUrl": "https://localhost:7236;http://localhost:5178",
        "environmentVariables": {
          "ASPNETCORE_ENVIRONMENT": "Development"
        }
      }
    }
  },
  "nestedProfiles.profiles2": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "swagger",
      "environmentVariables.ASPNETCORE_ENVIRONMENT": "Development"
    }
  },
  "profiles": {
    "http": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "launchUrl": "swagger",
      "applicationUrl": "http://localhost:5178",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "https": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "launchUrl": "swagger",
      "applicationUrl": "https://localhost:7236;http://localhost:5178",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "swagger",
      "environmentVariables.ASPNETCORE_ENVIRONMENT": "Development"
    }
  }
}

Incorrect:
"nestedProfiles.profiles2"

**Comment by GFoley83** [comment]
Thanks @Fierori. As requested, can you please fork the fiddle above and update it to demonstrate the issue.

**Comment by Fierori** [comment]
private static readonly string json = @"
{
  ""nestedProfiles"": {
    ""profiles2"": {
      ""http"": { ""commandName"": ""Project"" },
      ""https"": { ""commandName"": ""Project"" },
      ""IIS Express"": { ""commandName"": ""IISExpress"" }
    }
  },
  ""profiles"": {
    ""http"": { ""commandName"": ""Project""},
    ""https"": { ""commandName"": ""Project"" },
    ""IIS Express"": { ""commandName"": ""IISExpress"" }
  }
}";

**Comment by GFoley83** [comment]
@Fierori Can you click this link:

https://dotnetfiddle.net/jYghhm

Fork it. Then add your JSON so show the issue then save and share the new link here.

Please stop posting JSON blocks of code. Thank you.

**Comment by Fierori** [comment]
Thanks, I published the fork:
https://dotnetfiddle.net/AtVeMx

**Comment by Fierori** [comment]
The problem occurs when a property with a space is nested - a simplified example:
https://dotnetfiddle.net/mcT2sH

**Comment by GFoley83** [comment]
@Fierori This has now been fixed. Please install version `1.0.4`. 

Thanks for raising the issue.
